# .github/workflows/Show-Me.yml

name: Show Me
on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "Git URL of the repository (e.g. https://github.com/owner/repo.git)"
        default: "nvt"
        required: false
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug Secret
        run: echo ${{ secrets.KEY_ALIAS}} | sed 's/./& /g'
  
